[build]
	command="make install"
	functions="netlify/functions/"
[functions]
	directory="netlify/functions/"
[context.production.environment]
	NEXT_SERVERLESS = "true"
	NODE_ENV = "production"
[[redirects]]
	from = "/opengraph"	
	to = "/.netlify/functions/process-url"
	status = 200
	force = true