backend:
    name: git-gateway
    branch: main # Branch to update (optional; defaults to master)
media_folder: 'public/images'
public_folder: 'images'
collections:
    - name: 'posts'
      label: 'Posts'
      folder: 'posts'
      create: true
      slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
      fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - {
                label: 'Publish Date',
                name: 'date',
                widget: 'datetime',
                timeFormat: false,
                dateFormat: 'YYYY-MM-DD',
                format: 'LLL',
            }
          - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
          - { label: 'Rating (scale of 1-5)', name: 'rating', widget: 'number' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
